sudo: false
language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
env:
  - BP_NTP_TRAVISCI=travis:phpunit
matrix:
  include:
    - php: 7.1
      env: BP_NTP_TRAVISCI=travis:grunt
before_script:
  - mysql --version
  - php --version
  - phpenv versions
  - phpunit --version
  - node --version
  - nvm install 6
  - node --version
  - npm --version
  - npm install -g grunt-cli
  - grunt --version
  - npm install
script: grunt $BP_NTP_TRAVISCI
